- hosts: all
  gather_facts: false
  connection: community.aws.aws_ssm
  tasks:
    - name: Wait for connection to be available
      vars:
        ansible_connection: aws_ssm
        ansible_aws_ssm_bucket_name: gtempus_minecraft_files
        ansible_aws_ssm_region: us-east-2
        # When the S3 bucket isn't in the same region as the Instance
        # Explicitly setting the addressing style to 'virtual' may be necessary
        # https://repost.aws/knowledge-center/s3-http-307-response
        ansible_aws_ssm_s3_addressing_style: virtual
      tasks:
        - name: Wait for connection
          wait_for_connection: echo "Hello, world!"
