- name: simple task
  hosts: all
  gather_facts: false
  vars:
    ansible_connection: aws_ssm
    ansible_aws_ssm_bucket_name: gtempus-minecraft-server-ansible
    ansible_aws_ssm_region: us-east-2
    ansible_aws_ssm_instance_id: instance-id
    device_name: /dev/xvdf
    mount_point: /mnt/ebs_volume
  tasks:
    - name: Wait 60 seconds for target connection to become reachable/usable
      wait_for_connection:
        timeout: 60

    - name: List block devices
      ansible.builtin.command: lsblk
      register: lsblk_output

    - name: Show lsblk output
      ansible.builtin.debug:
        msg: "{{ lsblk_output.stdout }}"

    - name: Check if EBS Volume exists at given device name
      command: ls {{ device_name }}
      register: volume_check
      ignore_errors: yes

    - name: Create filesystem on EBS Volume if not exists
      filesystem:
        fstype: ext4
        dev: "{{ device_name }}"
      when: volume_check.rc != 0

    - name: Create mount point
      become: true
      file:
        path: "{{ mount_point }}"
        state: directory

    - name: Mount EBS Volume
      become: true
      mount:
        path: "{{ mount_point }}"
        src: "{{ device_name }}"
        fstype: ext4
        state: mounted
        opts: defaults,nofail
