- name: simple task
  hosts: all
  gather_facts: false
  vars:
    ansible_connection: aws_ssm
    ansible_aws_ssm_bucket_name: gtempus-minecraft-server-ansible
    ansible_aws_ssm_region: us-east-2
    ansible_aws_ssm_instance_id: instance-id
  tasks:
    - name: hello
      raw: echo "Hello, world!"
      tags: helo
