- name: simple task
  hosts: all
  gather_facts: false
  vars:
    ansible_connection: aws_ssm
    ansible_aws_ssm_region: us-east-2
    ansible_aws_ssm_instance_id: instance-id
    device_name: /dev/xvdf
    mount_point: /mnt/ebs_volume
  tasks:
    - name: Wait 60 seconds for target connection to become reachable/usable
      wait_for_connection:
        timeout: 120

    - name: Check existing filesystem on EBS Volume
      command: lsblk -f "{{ device_name }}"
      register: lsblk_f_output
      ignore_errors: true

    - name: Display lsblk output
      debug:
        msg: "{{ lsblk_f_output.stdout }}"

    - name: Create filesystem on EBS Volume
      become: true
      filesystem:
        fstype: ext4
        dev: "{{ device_name }}"

    - name: Create mount point
      become: true
      file:
        path: "{{ mount_point }}"
        state: directory

    - name: Mount EBS Volume
      become: true
      mount:
        path: "{{ mount_point }}"
        src: "{{ device_name }}"
        fstype: ext4
        state: mounted
        opts: defaults,nofail
