- name: install aws-cli
  hosts: all
  gather_facts: false
  vars:
    ansible_connection: aws_ssm
    ansible_aws_ssm_bucket_name: gtempus-minecraft-server-ansible
    ansible_aws_ssm_region: us-east-2
    ansible_aws_ssm_instance_id: i-030c66541aab831f5
  tasks:
    - name: aws-cli
      raw: yum install -y awscli
      tags: aws-cli
