- name: simple task
  hosts: all
  gather_facts: false
  vars:
    ansible_python_interpreter: "/usr/bin/python3"
    ansible_connection: aws_ssm
    ansible_aws_ssm_bucket_name: gtempus-minecraft-server-ansible
    ansible_aws_ssm_region: us-east-2
    ansible_aws_ssm_instance_id: instance-id
    device_name: /dev/xvdf
    mount_point: /mnt/ebs_volume
    s3_minecraft_file: 'bedrock-server-1.20.51.01.zip'
    local_path: '/tmp/bedrock-server.zip'
    minecraft_server_directory: "{{ mount_point }}/minecraft"
    extraction_path: "{{ minecraft_server_directory }}"
    s3_minecraft_systemd_file: 'minecraft.service'
  tasks:
    - name: Stop minecraft server service
      become: true
      ansible.builtin.service:
        name: "{{ s3_minecraft_systemd_file }}"
        state: stopped
