name: API Triggered Workflow

on:
  repository_dispatch:
    types: [custom_event]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Print the payload
        run: echo "${{ github.event.client_payload }}"

    # Add more steps as needed...
